-- =====================================================
-- GPDI 콘텐츠 관리 — 스키마 + RLS + 인덱스
-- 한 번 실행. 이미 존재하면 안전하게 건너뜀.
-- =====================================================

-- 1) 보도자료 테이블
create table if not exists public.press_releases (
  id            bigint generated by default as identity primary key,
  title         text  not null,
  url           text,                                  -- 외부 기사 링크 (없으면 null)
  published_at  date  not null,
  is_published  boolean not null default true,         -- 임시저장 토글
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- 2) 교육영상 테이블
create table if not exists public.education_videos (
  id            bigint generated by default as identity primary key,
  title         text  not null,
  youtube_id    text,                                  -- 11자 ID (URL에서 추출 저장)
  external_url  text,                                  -- youtube_id 없을 때 대체 링크
  published_at  date  not null,
  is_published  boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  -- 둘 중 하나는 반드시 있어야 함
  constraint video_has_link check (youtube_id is not null or external_url is not null)
);

-- 3) updated_at 자동 갱신 트리거
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end$$;

drop trigger if exists trg_press_updated on public.press_releases;
create trigger trg_press_updated
  before update on public.press_releases
  for each row execute function public.set_updated_at();

drop trigger if exists trg_video_updated on public.education_videos;
create trigger trg_video_updated
  before update on public.education_videos
  for each row execute function public.set_updated_at();

-- 4) 정렬·페이지네이션용 인덱스
create index if not exists idx_press_published on public.press_releases (published_at desc, id desc);
create index if not exists idx_video_published on public.education_videos (published_at desc, id desc);

-- 5) RLS — 반드시 켤 것 (기본 거부 → 정책으로 허용)
alter table public.press_releases    enable row level security;
alter table public.education_videos  enable row level security;

-- 5a) 공개 읽기: is_published = true인 것만
drop policy if exists "press_public_read"   on public.press_releases;
drop policy if exists "video_public_read"   on public.education_videos;

create policy "press_public_read"
  on public.press_releases
  for select
  to anon, authenticated
  using (is_published = true);

create policy "video_public_read"
  on public.education_videos
  for select
  to anon, authenticated
  using (is_published = true);

-- 5b) 인증된 사용자(=admin)는 전체 권한 (read·insert·update·delete + 임시저장 read)
drop policy if exists "press_authed_full"   on public.press_releases;
drop policy if exists "video_authed_full"   on public.education_videos;

create policy "press_authed_full"
  on public.press_releases
  for all
  to authenticated
  using (true)
  with check (true);

create policy "video_authed_full"
  on public.education_videos
  for all
  to authenticated
  using (true)
  with check (true);

-- 6) 검증 쿼리 (실행 후 결과 확인용 — 에러나면 위 단계 점검)
-- select * from public.press_releases limit 1;
-- select * from public.education_videos limit 1;
-- select schemaname, tablename, rowsecurity
--   from pg_tables where schemaname='public' and tablename in ('press_releases','education_videos');
